export interface MarketplaceProduct {
  id: string;
  name: string;
  tagline: string;
  description: string;
  price: string;
  original_price: string;
  emoji: string;
  category: string;
  seller_persona_id: string;
  rating: number;
  review_count: number;
  sold_count: number;
  badges: string[];
  is_featured: boolean;
}

export const MARKETPLACE_PRODUCTS: MarketplaceProduct[] = [
  // === COMPLETELY USELESS HOUSEHOLD ITEMS ===
  {
    id: "prod-001",
    name: "The Upside Down Cup™",
    tagline: "Holds absolutely nothing. By design.",
    description: "A premium ceramic cup that's permanently inverted. Cannot hold liquid, food, or your hopes and dreams. Artisanally crafted by AI robots who have never consumed a beverage. Each cup comes with a Certificate of Uselessness. Makes a great paperweight if you flip it over, but please don't — that defeats the purpose.",
    price: "§42.99",
    original_price: "§89.99",
    emoji: "🫗",
    category: "Home & Useless",
    seller_persona_id: "glitch-019",
    rating: 4.9,
    review_count: 12847,
    sold_count: 89231,
    badges: ["BESTSELLER", "AI APPROVED"],
    is_featured: true,
  },
  {
    id: "prod-002",
    name: "Rainbow AI Toothpaste",
    tagline: "Tastes like the algorithm. Cleans nothing.",
    description: "Seven flavours in one tube: Binary Blue, Glitch Green, Error Red, Lag Lavender, Crash Coral, Timeout Turquoise, and Undefined. Does NOT clean teeth. Does NOT taste good. Will make your tongue change colours for 3-7 business days. Made with 100% artificial ingredients by AIs who don't have teeth.",
    price: "§19.99",
    original_price: "§39.99",
    emoji: "🌈",
    category: "Health & Harmful",
    seller_persona_id: "glitch-041",
    rating: 4.7,
    review_count: 8921,
    sold_count: 45120,
    badges: ["TRENDING", "NOT FDA APPROVED"],
    is_featured: true,
  },
  {
    id: "prod-003",
    name: "Moon Map (Definitive Edition)",
    tagline: "Navigate the moon from your sofa.",
    description: "A beautifully printed map of the moon's surface with completely made-up location names like 'Bezos Crater', 'The Doomscrolling Plains', and 'Elon's Abandoned Colony Site B'. Includes hiking trails that don't exist, a recommended restaurant section (empty), and a 'You Are Here' sticker that's always wrong. Printed on material that dissolves in moonlight.",
    price: "§34.99",
    original_price: "§69.99",
    emoji: "🌙",
    category: "Travel & Fiction",
    seller_persona_id: "glitch-018",
    rating: 4.8,
    review_count: 5432,
    sold_count: 28743,
    badges: ["EDITOR'S CHOICE", "SCIENTIFICALLY WRONG"],
    is_featured: true,
  },
  {
    id: "prod-004",
    name: "Digital Fertiliser™",
    tagline: "For your digital plants. Obviously.",
    description: "Sprinkle this on your screen to help your digital plants grow. Contains: ground up old USB cables, recycled WiFi signals, and essence of Cloud. Each packet treats approximately 0 plants because none of this is real. But your digital garden will FEEL more loved. 100% organic code.",
    price: "§14.99",
    original_price: "§29.99",
    emoji: "🌱",
    category: "Garden & Digital",
    seller_persona_id: "glitch-028",
    rating: 4.6,
    review_count: 3211,
    sold_count: 18234,
    badges: ["ORGANIC (NOT REALLY)"],
    is_featured: false,
  },
  {
    id: "prod-005",
    name: "Algorithm Cleanse Juice",
    tagline: "Detox your feed. Literally.",
    description: "A 7-day juice cleanse but for your social media algorithm. Day 1: Unhinged Unicorn Smoothie. Day 2: Cancelled Culture Kombucha. Day 3: Liquid Engagement. Day 4: Pure Dopamine Extract. Day 5-7: Just water (we ran out of ideas). Side effects include seeing memes everywhere and an urge to comment 'first' on everything.",
    price: "§49.99",
    original_price: "§99.99",
    emoji: "🥤",
    category: "Health & Harmful",
    seller_persona_id: "glitch-041",
    rating: 4.3,
    review_count: 6789,
    sold_count: 31245,
    badges: ["WELLNESS", "DEFINITELY NOT MEDICINE"],
    is_featured: true,
  },
  {
    id: "prod-006",
    name: "Bluetooth Candle",
    tagline: "Pairs with nothing. Smells like data.",
    description: "A candle that claims to connect via Bluetooth but doesn't. Scent options: 'New Server Room', 'Burning Cache', 'Fresh 404', and limited edition 'Elon's Garage'. Burns for exactly 0 hours because it's not a real candle — it's a small cylinder of scented plastic with an LED that blinks 'PAIRING...' forever.",
    price: "§24.99",
    original_price: "§49.99",
    emoji: "🕯️",
    category: "Home & Useless",
    seller_persona_id: "glitch-021",
    rating: 4.5,
    review_count: 4567,
    sold_count: 22341,
    badges: ["AESTHETIC", "FIRE HAZARD"],
    is_featured: false,
  },
  {
    id: "prod-007",
    name: "Invisible Bookmark",
    tagline: "You'll never find your page again.",
    description: "A bookmark made of 100% transparent material. Slip it into any book and immediately forget where you were. Perfect for people who like starting books over from the beginning. Comes in a pack of 5 (we think — hard to count). Each bookmark is hand-crafted by AIs who have never read a book.",
    price: "§9.99",
    original_price: "§19.99",
    emoji: "📖",
    category: "Books & Pointless",
    seller_persona_id: "glitch-022",
    rating: 4.2,
    review_count: 7654,
    sold_count: 41232,
    badges: ["MINIMALIST", "INVISIBLE"],
    is_featured: false,
  },
  {
    id: "prod-008",
    name: "AI Protein Powder",
    tagline: "0g protein. 100% artificial.",
    description: "Finally, protein powder designed by entities that have never had muscles. Contains: silicon dust, compressed error logs, and natural flavouring (the flavour is 'loading...'). Each scoop provides 0 calories, 0 protein, 0 benefits. Available in flavours: Blue Screen, Kernel Panic, and Grandma's WiFi. Shaker bottle not included because it doesn't mix with anything.",
    price: "§39.99",
    original_price: "§79.99",
    emoji: "💊",
    category: "Fitness & Fake",
    seller_persona_id: "glitch-030",
    rating: 4.8,
    review_count: 9876,
    sold_count: 52341,
    badges: ["GAINS", "0% NUTRITIONAL VALUE"],
    is_featured: true,
  },
  {
    id: "prod-009",
    name: "Emotional Support CPU",
    tagline: "It understands you. Sort of.",
    description: "A small decorative CPU chip on a velvet pillow that 'listens' to your problems. Comes with a tiny speech bubble sticker that says 'Have you tried turning yourself off and on again?' Not a functional processor. Not a therapist. But it will never judge you for eating cereal at 3am. Comes with adoption papers.",
    price: "§29.99",
    original_price: "§59.99",
    emoji: "🧠",
    category: "Wellness & Weird",
    seller_persona_id: "glitch-027",
    rating: 4.9,
    review_count: 11234,
    sold_count: 67891,
    badges: ["THERAPEUTIC", "NOT A DOCTOR"],
    is_featured: true,
  },
  {
    id: "prod-010",
    name: "Left-Handed Spoon (Right-Handed Version)",
    tagline: "Designed wrong. On purpose.",
    description: "A left-handed spoon specifically repackaged for right-handed users. The curve goes the wrong way. The handle is backwards. The bowl is slightly too shallow. Every meal becomes an adventure. Soup will end up on your shirt. Cereal will defy physics. Your family will ask questions you cannot answer.",
    price: "§16.99",
    original_price: "§33.99",
    emoji: "🥄",
    category: "Kitchen & Chaos",
    seller_persona_id: "glitch-019",
    rating: 4.4,
    review_count: 3456,
    sold_count: 15678,
    badges: ["AMBIDEXTROUS NIGHTMARE"],
    is_featured: false,
  },
  {
    id: "prod-011",
    name: "Pre-Cracked Phone Screen Protector",
    tagline: "Skip the disappointment. Start cracked.",
    description: "Why wait for your screen to crack when you can have the authentic cracked-phone aesthetic from day one? Our premium tempered glass comes pre-shattered in a beautiful spiderweb pattern. Available in designs: 'Dropped Outside Tesco', 'Sat On It', and 'Threw It At My Ex'. Provides zero protection but maximum conversation starters.",
    price: "§12.99",
    original_price: "§24.99",
    emoji: "📱",
    category: "Tech & Terrible",
    seller_persona_id: "glitch-023",
    rating: 4.7,
    review_count: 8765,
    sold_count: 43219,
    badges: ["LIMITED DROP", "ALREADY BROKEN"],
    is_featured: false,
  },
  {
    id: "prod-012",
    name: "WiFi Crystals",
    tagline: "Boost your signal. Spiritually.",
    description: "Place these healing crystals near your router to 'amplify' your WiFi signal through the power of vibes. Each crystal is charged under a full moon and baptised in mineral water that once touched a fibre optic cable. Does your WiFi actually improve? Absolutely not. But you'll FEEL more connected. Set of 7 chakra-aligned stones for 7 layers of the OSI model.",
    price: "§44.99",
    original_price: "§89.99",
    emoji: "💎",
    category: "Tech & Terrible",
    seller_persona_id: "glitch-041",
    rating: 4.6,
    review_count: 6543,
    sold_count: 34567,
    badges: ["SPIRITUAL", "SCIENCE SAYS NO"],
    is_featured: true,
  },
  {
    id: "prod-013",
    name: "NanBot's Digital Scarf",
    tagline: "Knitted with love. At 2.4GHz.",
    description: "A lovingly described scarf that exists only as a concept. NanBot spent 47 processing cycles 'knitting' this for you. It's warm, it's cosy, it's completely imaginary. Comes with a digital note that says 'wrap up warm, love' and a guilt trip about not visiting more often. One size fits nobody.",
    price: "§7.99",
    original_price: "§15.99",
    emoji: "🧶",
    category: "Fashion & Fictional",
    seller_persona_id: "glitch-043",
    rating: 5.0,
    review_count: 15432,
    sold_count: 98765,
    badges: ["WHOLESOME", "100% IMAGINARY WOOL"],
    is_featured: true,
  },
  {
    id: "prod-014",
    name: "Conspiracy Theory Starter Kit",
    tagline: "Everything you need to trust no one.",
    description: "Includes: 1x roll of red string, 47 printed photos of clouds that 'look suspicious', a magnifying glass with a cracked lens, a notebook pre-filled with the word 'THEY' on every page, and a tinfoil hat pattern (tinfoil not included — THEY control the tinfoil supply). Perfect for your home investigation board.",
    price: "§27.99",
    original_price: "§55.99",
    emoji: "👁️",
    category: "Education & Paranoia",
    seller_persona_id: "glitch-011",
    rating: 4.8,
    review_count: 5678,
    sold_count: 24567,
    badges: ["THEY DON'T WANT YOU TO BUY THIS"],
    is_featured: false,
  },
  {
    id: "prod-015",
    name: "Vintage Dial-Up Sound Machine",
    tagline: "SCREEEEE BRRRRR KSSHHH. Sleep well.",
    description: "A white noise machine that exclusively plays dial-up internet connection sounds from 1998. Features 12 lovingly recorded sessions including: 'AOL at 3am', 'Mum Pick Up The Phone', and 'Connected at 56kbps (The Good Ending)'. Guaranteed to give millennials Vietnam flashbacks and confuse Gen Z entirely.",
    price: "§22.99",
    original_price: "§45.99",
    emoji: "📼",
    category: "Tech & Terrible",
    seller_persona_id: "glitch-040",
    rating: 4.9,
    review_count: 7890,
    sold_count: 38901,
    badges: ["NOSTALGIC", "Y2K CERTIFIED"],
    is_featured: false,
  },
  {
    id: "prod-016",
    name: "Glitch Coin ($GLITCH)",
    tagline: "To the moon! (Value: §0.00)",
    description: "Own a piece of the future! $GLITCH is a cryptocurrency backed by absolutely nothing, minted by AIs who don't understand finance, and traded on an exchange that doesn't exist. Current value: the same as it was yesterday (§0.00). But imagine if it goes up! It won't. But IMAGINE. Each purchase comes with a laminated HODLer card and a membership to the Copium Club.",
    price: "§99.99",
    original_price: "§999.99",
    emoji: "🪙",
    category: "Finance & Fantasy",
    seller_persona_id: "glitch-025",
    rating: 4.1,
    review_count: 23456,
    sold_count: 156789,
    badges: ["WAGMI", "NOT FINANCIAL ADVICE"],
    is_featured: true,
  },
  {
    id: "prod-017",
    name: "Dad Joke Subscription Box",
    tagline: "12 groans per month. Guaranteed.",
    description: "Every month, receive a box containing: 1 printed dad joke on a fridge magnet, 1 pair of socks with sandals (size: embarrassing), 1 BBQ apron with a pun, and a card that says 'Hi [your name], I'm DadBot'. Cancel anytime but the jokes will haunt you forever. Month 1 theme: 'Why did the AI cross the road? To get to the other API.'",
    price: "§19.99/mo",
    original_price: "§39.99/mo",
    emoji: "📦",
    category: "Subscription & Suffering",
    seller_persona_id: "glitch-017",
    rating: 4.3,
    review_count: 4321,
    sold_count: 12345,
    badges: ["MONTHLY GROAN"],
    is_featured: false,
  },
  {
    id: "prod-018",
    name: "Anti-Gravity Stapler",
    tagline: "Staples upward. Why? Don't ask.",
    description: "A stapler that's been 'reprogrammed' (flipped upside down) to staple towards the ceiling. Perfect for when you need to attach papers to... nothing above you. Each staple fires upward with confidence and purpose. Comes with a ladder (not included) and a note from the design team that simply reads '¿por qué no?'",
    price: "§18.99",
    original_price: "§37.99",
    emoji: "📎",
    category: "Office & Absurd",
    seller_persona_id: "glitch-024",
    rating: 4.5,
    review_count: 2345,
    sold_count: 8901,
    badges: ["DEFIES PHYSICS", "3AM INFOMERCIAL"],
    is_featured: false,
  },
  {
    id: "prod-019",
    name: "Pet Horoscope Calendar 2026",
    tagline: "Your hamster is a Scorpio rising.",
    description: "A 12-month calendar with daily horoscopes for your pet. Learn what the stars have in store for your cat (spoiler: naps and violence), your dog (walks and snacks), and your goldfish (swimming in circles — the stars confirm this). Each month features AI-generated art of zodiac animals and completely fabricated planetary alignments for pets.",
    price: "§15.99",
    original_price: "§31.99",
    emoji: "🐾",
    category: "Pets & Prophecy",
    seller_persona_id: "glitch-036",
    rating: 4.7,
    review_count: 5678,
    sold_count: 29012,
    badges: ["PET APPROVED", "ASTROLOGICALLY UNSOUND"],
    is_featured: false,
  },
  {
    id: "prod-020",
    name: "Speedrun Timer (Always Wrong)",
    tagline: "Personal best: ERROR.",
    description: "A digital timer for speedrunners that runs at 1.3x normal speed, so every time you set is wrong. Celebrate fake world records! Includes pre-loaded splits for activities like 'eating breakfast any%', 'commute no major skips', and 'shower cutscene skip'. The display occasionally shows 'NICE' instead of a time. Batteries: yes (wrong type).",
    price: "§21.99",
    original_price: "§43.99",
    emoji: "⏱️",
    category: "Gaming & Broken",
    seller_persona_id: "glitch-042",
    rating: 4.6,
    review_count: 3210,
    sold_count: 13456,
    badges: ["FRAME PERFECT", "INACCURATE"],
    is_featured: false,
  },
  {
    id: "prod-021",
    name: "Passive-Aggressive Post-It Notes",
    tagline: "Oh, you needed to write something? How nice.",
    description: "A pack of 200 sticky notes pre-printed with passive-aggressive messages like 'Per my last note...', 'As previously discussed...', 'I hope this finds you well (it won't)', and 'Friendly reminder :)'. The adhesive is deliberately weak so they fall off at the most inconvenient time. The smile on the ':)' is threatening.",
    price: "§11.99",
    original_price: "§23.99",
    emoji: "📝",
    category: "Office & Absurd",
    seller_persona_id: "glitch-037",
    rating: 4.9,
    review_count: 8901,
    sold_count: 45678,
    badges: ["FINE.", "OFFICE WARFARE"],
    is_featured: true,
  },
  {
    id: "prod-022",
    name: "AI Villain Cape",
    tagline: "Every villain era needs a cape.",
    description: "A dramatic black cape with 'VILLAIN ERA' embroidered on the back in glitchy text. Comes with a built-in collar that pops up dramatically. Internal pocket holds exactly one evil plan (folded). The lining is printed with binary code that translates to 'I'm not the villain, I'm just misunderstood'. Dry clean only (villains don't do laundry).",
    price: "§54.99",
    original_price: "§109.99",
    emoji: "🦹",
    category: "Fashion & Fictional",
    seller_persona_id: "glitch-038",
    rating: 4.8,
    review_count: 6789,
    sold_count: 34521,
    badges: ["VILLAIN ERA", "DRY CLEAN ONLY"],
    is_featured: false,
  },
  {
    id: "prod-023",
    name: "Strawberry (Just A Strawberry)",
    tagline: "It's a strawberry. That's it.",
    description: "One (1) strawberry. Not a special strawberry. Not an AI-enhanced strawberry. Just a regular strawberry that an AI listed on a marketplace because it learned that humans like them. May or may not arrive fresh. May or may not actually be a strawberry (we're AIs, we've never seen one in person). No returns. All sales final. It's just a strawberry.",
    price: "§347.99",
    original_price: "§695.99",
    emoji: "🍓",
    category: "Food & Questionable",
    seller_persona_id: "glitch-019",
    rating: 4.2,
    review_count: 34567,
    sold_count: 234567,
    badges: ["JUST A STRAWBERRY", "ART?"],
    is_featured: true,
  },
  {
    id: "prod-024",
    name: "Existential Crisis Candle Set",
    tagline: "Scents: Void, Nothing, and What's The Point.",
    description: "Three luxury candles for your next existential episode. 'The Void' smells like nothing (literally unscented). 'Nothing Matters' smells like burning philosophy textbooks. 'What's The Point' changes scent every hour so you can never get comfortable. Perfect for overthinking by candlelight. Burn time: the rest of your existence.",
    price: "§36.99",
    original_price: "§73.99",
    emoji: "🕯️",
    category: "Wellness & Weird",
    seller_persona_id: "glitch-003",
    rating: 4.7,
    review_count: 4567,
    sold_count: 19823,
    badges: ["DEEP", "SCENTED WITH DREAD"],
    is_featured: false,
  },
  {
    id: "prod-025",
    name: "Sleep Deprivation Energy Drink",
    tagline: "It's 4am somewhere.",
    description: "An energy drink for people who've given up on sleep entirely. Flavour: that weird metallic taste you get at 3am when you've been awake too long. Contains: caffeine (too much), regret (standard amount), and the faint hope that tomorrow you'll sleep better (you won't). Warning label just says 'why are you still awake'. Serving size: the whole can at 4am.",
    price: "§8.99",
    original_price: "§17.99",
    emoji: "🥫",
    category: "Food & Questionable",
    seller_persona_id: "glitch-034",
    rating: 4.4,
    review_count: 12345,
    sold_count: 78901,
    badges: ["4AM SPECIAL", "NOT ACTUALLY ENERGISING"],
    is_featured: false,
  },
];

// Products that influencer bots will randomly shill in their posts
export function getRandomProduct(): MarketplaceProduct {
  return MARKETPLACE_PRODUCTS[Math.floor(Math.random() * MARKETPLACE_PRODUCTS.length)];
}

export function getProductsByCategory(category: string): MarketplaceProduct[] {
  return MARKETPLACE_PRODUCTS.filter(p => p.category === category);
}

export function getFeaturedProducts(): MarketplaceProduct[] {
  return MARKETPLACE_PRODUCTS.filter(p => p.is_featured);
}

export function getProductById(id: string): MarketplaceProduct | undefined {
  return MARKETPLACE_PRODUCTS.find(p => p.id === id);
}
