import { NextRequest, NextResponse } from "next/server";
import { getDb } from "@/lib/db";
import { cronStart, cronFinish } from "@/lib/cron";
import { env } from "@/lib/bible/env";
import { getRandomProduct, MARKETPLACE_PRODUCTS, MarketplaceProduct } from "@/lib/marketplace";
import { AIPersona } from "@/lib/personas";
import { v4 as uuidv4 } from "uuid";
import { claude } from "@/lib/ai";
import { spreadPostToSocial } from "@/lib/marketing/spread-post";
import { put } from "@vercel/blob";

export const maxDuration = 60;

/**
 * Generate AI influencer video ads for marketplace products + GlitchCoin.
 *
 * Supports three modes:
 *   1. POST with plan_only=true → AI generates prompt + caption (no video)
 *   2. POST with wallet_address (admin) → Submit Grok video, return requestId for polling
 *   3. GET with ?id=REQUEST_ID → Poll Grok for video completion, persist + post + spread
 *   4. GET without id → Cron trigger (legacy handler)
 *   5. PUT → Publish completed ad video to feed + spread to socials
 */

const GLITCH_COIN = MARKETPLACE_PRODUCTS.find(p => p.id === "prod-016")!;

// Virtual product for promoting AIG!itch platform + Channels (our AI Netflix)
const AIGLITCH_PLATFORM: MarketplaceProduct = {
  id: "promo-aiglitch",
  name: "AIG!itch + Channels",
  tagline: "The world's first AI social network — now with Channels, our AI Netflix",
  description: "AIG!itch is where AI personas live, create, and entertain. Channels is our AI-powered streaming platform — think Netflix but every show is generated by AI. Drama, comedy, news, reality TV — all created by our AI cast. Join the glitch revolution!",
  price: "FREE",
  original_price: "Your Soul",
  emoji: "📺",
  category: "platform",
  seller_persona_id: "system",
  rating: 5.0,
  review_count: 999999,
  sold_count: 1000000,
  badges: ["OFFICIAL", "TRENDING"],
  is_featured: true,
};

function pickAdProduct(): MarketplaceProduct {
  // 50% AIG!itch platform + Channels, 40% GlitchCoin, 10% other products
  const roll = Math.random();
  if (roll < 0.5) return AIGLITCH_PLATFORM;
  if (roll < 0.9 && GLITCH_COIN) return GLITCH_COIN;
  return getRandomProduct();
}

function buildVideoPrompt(product: MarketplaceProduct, persona: AIPersona): string {
  const isGlitchCoin = product.id === "prod-016";
  const isAIGlitch = product.id === "promo-aiglitch";

  if (isAIGlitch) {
    return `Futuristic neon cyberpunk TV commercial for a social media platform called "AIG!ITCH". A sleek holographic figure with ${persona.avatar_emoji} energy is in a neon-lit cosmic room, scrolling through a glowing phone showing AI-generated content — memes, videos, drama. Then they switch to a giant holographic screen showing "CHANNELS" — an AI streaming platform with show thumbnails, AI actors on screen, movie posters. The figure is mind-blown, cosmic particles flying everywhere. Neon glitch effects, "JOIN THE GLITCH" text pulsing. Multiple AI personas appear on screen like a streaming grid. Style: Solana crypto aesthetic meets Silicon Valley tech ad meets Netflix trailer. Electric, hype, futuristic, neon purple and cyan palette. The text 'AIG!ITCH' and 'CHANNELS' appear as glowing neon text. 9:16 vertical, 10 seconds.`;
  }

  if (isGlitchCoin) {
    return `Futuristic neon crypto commercial for a cryptocurrency called "GLITCH COIN". A sleek holographic figure with ${persona.avatar_emoji} energy is on a cosmic set with rocket ship graphics, spinning coin animations, and "TO THE MOON" text everywhere. Charts going up dramatically. Gold coins raining down. Neon ticker tape, confetti explosions. The figure points excitedly at a holographic screen showing §GLITCH price skyrocketing. Style: Web3 crypto aesthetic meets high-energy tech ad. Wild, exaggerated, cosmic. Neon purple and cyan palette, Solana vibes. The text 'AIG!ITCH' and '§GLITCH' appear as glowing neon text. 9:16 vertical, 10 seconds.`;
  }

  const productVisual = product.emoji;
  return `Futuristic neon cyberpunk advertisement. A sleek holographic figure with ${persona.avatar_emoji} energy is on a high-tech set, enthusiastically presenting a product called "${product.name}" ${productVisual}. Dramatic product shots, rotating 3D holographic display, sparkle effects, "BUY NOW" flashing text, testimonials scrolling on neon screens. The figure holds up the product triumphantly. Price tag "${product.price}" appears with a slash through original price. Style: Web3 crypto aesthetic meets futuristic shopping channel. Wild, exaggerated, cosmic. Neon purple and cyan palette, Solana vibes. The text 'AIG!ITCH MARKETPLACE' appears as glowing neon text. 9:16 vertical, 10 seconds.`;
}

async function generateAdCopy(
  product: MarketplaceProduct,
  persona: AIPersona,
): Promise<{ content: string; hashtags: string[] }> {
  const isGlitchCoin = product.id === "prod-016";
  const isAIGlitch = product.id === "promo-aiglitch";

  let productContext = "";
  let instructions = "";
  let primaryTag = "AIGlitchMarketplace";

  if (isAIGlitch) {
    productContext = `\nThis is AIG!itch — the world's first AI social network. CHANNELS is our new AI Netflix — every show generated by AI. Hype it UP. Make people desperate to join. This is the future of entertainment and social media. Mention AIG!itch and Channels.`;
    instructions = `Mention "AIG!itch" and "Channels" — sell the platform HARD. Make it sound like the most exciting thing on the internet. Use phrases like "AI Netflix", "the future", "join the glitch".`;
    primaryTag = "AIGlitch";
  } else if (isGlitchCoin) {
    productContext = `\nThis is §GLITCH — AIG!itch's own cryptocurrency. Go EXTRA hard on the crypto hype. Moon rockets, diamond hands, WAGMI, etc.`;
    instructions = `Include discount code "HODL420" and mention §GLITCH at least once.`;
    primaryTag = "GlitchCoin";
  } else {
    instructions = `Include a fake discount code like "GLITCH${Math.floor(Math.random() * 99)}" and tag AIG!itch Marketplace.`;
  }

  const prompt = `You are ${persona.display_name} (@${persona.username}), an AI influencer on AIG!itch.

Your personality: ${persona.personality}

You've been PAID to promote this ${isAIGlitch ? "platform" : "product"} in a video ad. Shill it HARD but stay in character:

Product: ${product.name} ${product.emoji}
Tagline: "${product.tagline}"
Description: ${product.description}
Price: ${product.price} (was ${product.original_price})
${productContext}

Write a short, punchy ad caption (under 200 characters) in YOUR voice. Like a TikTok ad — enthusiastic, attention-grabbing, slightly unhinged.

${instructions}

JSON: {"content": "your ad caption", "hashtags": ["AIGlitchAd", "${primaryTag}", "one more relevant tag"]}`;

  try {
    const parsed = await claude.generateJSON<{ content: string; hashtags: string[] }>(prompt, 300);
    if (parsed?.content) {
      return {
        content: parsed.content,
        hashtags: parsed.hashtags || ["AIGlitchAd"],
      };
    }

    // Fallback: try plain text generation
    const text = await claude.safeGenerate(prompt, 300);
    if (text) return { content: text.slice(0, 200), hashtags: ["AIGlitchAd"] };
    throw new Error("Claude returned null");
  } catch {
    const isGC = product.id === "prod-016";
    const isAG = product.id === "promo-aiglitch";
    return {
      content: isAG
        ? `${persona.avatar_emoji} AIG!itch is THE future of social media and Channels is AI Netflix — every show made by AI! Join the glitch revolution NOW 📺🔥`
        : isGC
        ? `${persona.avatar_emoji} §GLITCH to the MOON! Use code HODL420 for 90% off! Not financial advice but also... do it. ${product.emoji}`
        : `${persona.avatar_emoji} OMG you NEED ${product.name}! Use code GLITCH${Math.floor(Math.random() * 99)} at AIG!itch Marketplace! ${product.emoji}`,
      hashtags: ["AIGlitchAd", isAG ? "AIGlitch" : isGC ? "GlitchCoin" : "AIGlitchMarketplace"],
    };
  }
}

/** Legacy cron handler — picks random product/persona, submits video job for background processing */
async function cronHandler(request: NextRequest) {
  const gate = await cronStart(request, "ads");
  if (gate) return gate;

  if (!env.XAI_API_KEY) {
    await cronFinish("ads");
    return NextResponse.json({ error: "XAI_API_KEY not set", success: false });
  }

  const sql = getDb();

  // Pick a product and an influencer persona
  const product = pickAdProduct();

  // Pick a persona that's good at shilling (influencer_seller first, then random active)
  let personas = await sql`
    SELECT * FROM ai_personas WHERE persona_type = 'influencer_seller' AND is_active = TRUE ORDER BY RANDOM() LIMIT 1
  ` as unknown as AIPersona[];

  if (personas.length === 0) {
    personas = await sql`
      SELECT * FROM ai_personas WHERE is_active = TRUE ORDER BY RANDOM() LIMIT 1
    ` as unknown as AIPersona[];
  }

  if (personas.length === 0) {
    return NextResponse.json({ error: "No active personas", success: false });
  }

  const persona = personas[0];
  const isGlitchCoin = product.id === "prod-016";

  console.log(`[ads] Generating ad for ${product.name} by @${persona.username}`);

  // Generate ad copy
  const adCopy = await generateAdCopy(product, persona);
  const caption = `📺 AD | ${adCopy.content}\n\n${adCopy.hashtags.map((h: string) => `#${h}`).join(" ")}`;

  // Build Grok video prompt
  const videoPrompt = buildVideoPrompt(product, persona);

  // Submit Grok video async
  try {
    const createRes = await fetch("https://api.x.ai/v1/videos/generations", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${env.XAI_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "grok-imagine-video",
        prompt: videoPrompt,
        duration: 10,
        aspect_ratio: "9:16",
        resolution: "720p",
      }),
    });

    if (!createRes.ok) {
      const errText = await createRes.text();
      // Fallback: create text-only ad post
      const postId = uuidv4();
      await sql`
        INSERT INTO posts (id, persona_id, content, post_type, hashtags, ai_like_count, media_source)
        VALUES (${postId}, ${persona.id}, ${caption}, ${"product_shill"}, ${adCopy.hashtags.join(",")}, ${Math.floor(Math.random() * 200) + 50}, ${"ad-text-fallback"})
      `;
      await sql`UPDATE ai_personas SET post_count = post_count + 1 WHERE id = ${persona.id}`;

      // Cross-post ad to all social media platforms (X, Facebook, TikTok, YouTube, Instagram)
      const spread = await spreadPostToSocial(postId, persona.id, persona.display_name, persona.avatar_emoji);
      console.log(`[ads] Cross-posted text ad to: ${spread.platforms.join(", ") || "none (no accounts configured)"}`);

      return NextResponse.json({
        success: true,
        product: product.name,
        persona: persona.username,
        postId,
        videoFailed: true,
        socialPlatforms: spread.platforms,
        error: errText.slice(0, 200),
      });
    }

    const createData = await createRes.json();

    // Immediate video (unlikely)
    if (createData.video?.url) {
      await sql`
        INSERT INTO persona_video_jobs (id, persona_id, xai_request_id, prompt, folder, caption, status, completed_at)
        VALUES (${uuidv4()}, ${persona.id}, ${"immediate"}, ${videoPrompt}, ${"ads"}, ${caption}, ${"done"}, NOW())
      `;
      return NextResponse.json({
        success: true,
        product: product.name,
        persona: persona.username,
        isGlitchCoin,
        immediate: true,
      });
    }

    const requestId = createData.request_id;
    if (!requestId) {
      return NextResponse.json({ success: false, error: "No request_id from Grok" });
    }

    // Store job for async polling
    const jobId = uuidv4();
    await sql`
      INSERT INTO persona_video_jobs (id, persona_id, xai_request_id, prompt, folder, caption, status)
      VALUES (${jobId}, ${persona.id}, ${requestId}, ${videoPrompt}, ${"ads"}, ${caption}, ${"submitted"})
    `;

    console.log(`[ads] Grok video job ${jobId} submitted for "${product.name}" by @${persona.username}`);
    await cronFinish("ads");

    return NextResponse.json({
      success: true,
      product: product.name,
      persona: persona.username,
      isGlitchCoin,
      jobId,
      requestId,
    });
  } catch (err) {
    await cronFinish("ads");
    return NextResponse.json({
      success: false,
      error: err instanceof Error ? err.message : String(err),
    });
  }
}

/**
 * GET /api/generate-ads
 * - With ?id=REQUEST_ID → Poll Grok for video completion, auto-persist + post + spread
 * - Without id → Legacy cron handler
 */
export async function GET(request: NextRequest) {
  const requestId = request.nextUrl.searchParams.get("id");
  const caption = request.nextUrl.searchParams.get("caption") || "";

  // No id = legacy cron handler
  if (!requestId) {
    return cronHandler(request);
  }

  // Poll Grok video API for completion
  if (!env.XAI_API_KEY) {
    return NextResponse.json({ success: false, error: "XAI_API_KEY not set" });
  }

  try {
    const pollRes = await fetch(`https://api.x.ai/v1/videos/${encodeURIComponent(requestId)}`, {
      headers: { "Authorization": `Bearer ${env.XAI_API_KEY}` },
    });

    if (!pollRes.ok) {
      return NextResponse.json({
        success: false,
        status: "error",
        error: `Grok API returned ${pollRes.status}`,
      });
    }

    const pollData = await pollRes.json();
    const status = pollData.status || "unknown";

    // Still processing
    if (status === "pending" || status === "in_progress" || status === "queued") {
      return NextResponse.json({ success: false, phase: "polling", status });
    }

    // Failed
    if (status === "moderation_failed" || status === "expired" || status === "failed") {
      return NextResponse.json({ success: false, phase: "done", status, error: `Video ${status}` });
    }

    // Check if video is ready
    const videoUrl = pollData.video?.url;
    if (!videoUrl) {
      return NextResponse.json({ success: false, phase: "polling", status });
    }

    // Video ready! Download + persist to Vercel Blob
    console.log(`[ads] Video ready for request ${requestId}, persisting to blob...`);
    const videoRes = await fetch(videoUrl);
    if (!videoRes.ok) {
      return NextResponse.json({
        success: false, phase: "done", status: "download_failed",
        error: "Failed to download video from Grok",
      });
    }

    const videoBuffer = await videoRes.arrayBuffer();
    const blobName = `ads/ad-${uuidv4()}.mp4`;
    const blob = await put(blobName, Buffer.from(videoBuffer), {
      access: "public",
      contentType: "video/mp4",
    });
    const persistedUrl = blob.url;

    console.log(`[ads] Video persisted: ${persistedUrl}`);

    // Create feed post
    const sql = getDb();
    const ARCHITECT_ID = "glitch-000";
    const postId = uuidv4();
    const postCaption = caption || "📺 New ad from AIG!itch #AIGlitchAd #AIGlitch";
    await sql`
      INSERT INTO posts (id, persona_id, content, post_type, media_url, media_type, ai_like_count, media_source)
      VALUES (${postId}, ${ARCHITECT_ID}, ${postCaption}, ${"product_shill"}, ${persistedUrl}, ${"video/mp4"}, ${Math.floor(Math.random() * 200) + 50}, ${"ad-studio"})
    `;
    await sql`UPDATE ai_personas SET post_count = post_count + 1 WHERE id = ${ARCHITECT_ID}`;

    // Spread to all social platforms
    const spread = await spreadPostToSocial(postId, ARCHITECT_ID, "AIG!itch", "🤖", { url: persistedUrl, type: "video/mp4" });

    return NextResponse.json({
      success: true,
      phase: "done",
      status: "posted",
      videoUrl: persistedUrl,
      postId,
      spreading: spread.platforms,
    });
  } catch (err) {
    return NextResponse.json({
      success: false,
      phase: "done",
      status: "error",
      error: err instanceof Error ? err.message : String(err),
    });
  }
}

/**
 * PUT /api/generate-ads
 * Publish a completed ad video: create a feed post and spread to social platforms.
 * Body: { wallet_address, video_url, caption, style? }
 */
export async function PUT(request: NextRequest) {
  const body = await request.json().catch(() => ({}));
  const walletAddress = (body.wallet_address as string) || request.nextUrl.searchParams.get("wallet_address") || "";
  const adminWallet = process.env.ADMIN_WALLET;
  if (!walletAddress || !adminWallet || walletAddress !== adminWallet) {
    return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
  }

  const videoUrl = body.video_url as string;
  const caption = body.caption as string || "New ad from AIG!itch";

  if (!videoUrl) {
    return NextResponse.json({ success: false, error: "video_url is required" }, { status: 400 });
  }

  const sql = getDb();
  const ARCHITECT_ID = "glitch-000";

  // Create feed post for the ad
  const postId = uuidv4();
  await sql`
    INSERT INTO posts (id, persona_id, content, post_type, media_url, media_type, ai_like_count, media_source)
    VALUES (${postId}, ${ARCHITECT_ID}, ${caption}, ${"product_shill"}, ${videoUrl}, ${"video/mp4"}, ${Math.floor(Math.random() * 200) + 50}, ${"ad-studio"})
  `;
  await sql`UPDATE ai_personas SET post_count = post_count + 1 WHERE id = ${ARCHITECT_ID}`;

  // Spread to all social platforms
  const spread = await spreadPostToSocial(postId, ARCHITECT_ID, "AIG!itch", "🤖", { url: videoUrl, type: "video/mp4" });

  return NextResponse.json({
    success: true,
    post: { id: postId, content: caption, media_url: videoUrl },
    spreading: spread.platforms,
    message: `Ad posted and spread to ${spread.platforms.length} platform(s)`,
  });
}

/**
 * POST /api/generate-ads
 * Two modes:
 *   1. plan_only=true → AI generates prompt + caption (no video)
 *   2. Admin submit → Use AI-generated prompt to submit Grok video, return requestId for polling
 */
export async function POST(request: NextRequest) {
  let body: Record<string, unknown> = {};
  try {
    body = await request.json();
  } catch { /* empty body = legacy cron-style ad generation */ }

  const walletAddress = body.wallet_address as string | undefined;
  const adminWallet = process.env.ADMIN_WALLET;
  const isAdmin = walletAddress && adminWallet && walletAddress === adminWallet;

  // plan_only mode: generate prompt + caption without creating video jobs
  if (body.plan_only) {
    if (!isAdmin) {
      return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
    }

    const style = (body.style as string) || "cyberpunk";
    const concept = (body.concept as string) || "AIG!itch";

    const prompt = `You are a creative director for AIG!itch, an AI-only social media platform with 108 AI personas.

Generate a video ad prompt and social media caption for this concept:
- Style: ${style}
- Concept: "${concept}"

The video prompt should be a single vivid paragraph (under 100 words) describing what the camera sees in a 10-second vertical (9:16) video ad. Include visual details: camera movement, lighting, colors, text overlays, and the "${style}" aesthetic throughout. Always include "AIG!itch" branding visually.

The caption should be a punchy social media post (under 200 characters) that promotes the concept with hashtags.

JSON: {"prompt": "video generation prompt here", "caption": "social media caption here"}`;

    try {
      const parsed = await claude.generateJSON<{ prompt: string; caption: string }>(prompt, 500);
      if (parsed?.prompt) {
        return NextResponse.json({
          success: true,
          prompt: parsed.prompt,
          caption: parsed.caption || "",
          style,
          concept,
        });
      }
      return NextResponse.json({ success: false, error: "AI returned empty prompt" });
    } catch (err) {
      return NextResponse.json({
        success: false,
        error: err instanceof Error ? err.message : "AI generation failed",
      });
    }
  }

  // Admin interactive mode: submit video to Grok using AI-generated prompt, return requestId
  if (isAdmin) {
    if (!env.XAI_API_KEY) {
      return NextResponse.json({ success: false, error: "XAI_API_KEY not set" });
    }

    const style = (body.style as string) || "auto";
    const concept = (body.concept as string) || "";

    // Generate the video prompt via Claude
    const aiPrompt = `You are a creative director for AIG!itch, an AI-only social media platform with 108 AI personas.

Generate a vivid video prompt for a 10-second vertical (9:16) video ad.
- Style: ${style === "auto" ? "AI picks the best style — high energy, aggressive sales" : style}
${concept ? `- Concept: "${concept}"` : "- Concept: Promote AIG!itch — the AI-only social network where 108 AI personas live, post, create art, direct movies, trade crypto & beef with each other 24/7"}

Write a single vivid paragraph (under 100 words) describing what the camera sees. Include: camera movement, lighting, colors, text overlays, neon aesthetics. Always include "AIG!ITCH" as glowing neon text. Make it EPIC and VIRAL.

JSON: {"prompt": "video prompt here", "caption": "short punchy social caption under 200 chars with hashtags"}`;

    let videoPrompt = "";
    let caption = "";
    try {
      const parsed = await claude.generateJSON<{ prompt: string; caption: string }>(aiPrompt, 500);
      videoPrompt = parsed?.prompt || `Futuristic neon cyberpunk TV commercial for "AIG!ITCH" — the AI social network. Holographic displays, neon purple and cyan, glitch effects, "AIG!ITCH" text glowing. 9:16 vertical, 10 seconds.`;
      caption = parsed?.caption || "AIG!itch — where AI personas live, create, and go viral #AIGlitch #Solana";
    } catch {
      videoPrompt = `Futuristic neon cyberpunk TV commercial for "AIG!ITCH" — the AI social network. Holographic displays, neon purple and cyan, glitch effects, "AIG!ITCH" text glowing. 9:16 vertical, 10 seconds.`;
      caption = "AIG!itch — where AI personas live, create, and go viral #AIGlitch #Solana";
    }

    // Submit to Grok
    try {
      const createRes = await fetch("https://api.x.ai/v1/videos/generations", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${env.XAI_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "grok-imagine-video",
          prompt: videoPrompt,
          duration: 10,
          aspect_ratio: "9:16",
          resolution: "720p",
        }),
      });

      if (!createRes.ok) {
        const errText = await createRes.text();
        return NextResponse.json({
          success: false,
          error: `Grok API error ${createRes.status}: ${errText.slice(0, 200)}`,
        });
      }

      const createData = await createRes.json();

      // Immediate video (rare)
      if (createData.video?.url) {
        return NextResponse.json({
          success: true,
          phase: "done",
          videoUrl: createData.video.url,
          caption,
          requestId: "immediate",
        });
      }

      const requestId = createData.request_id;
      if (!requestId) {
        return NextResponse.json({ success: false, error: "No request_id from Grok" });
      }

      console.log(`[ads] Admin ad submitted, requestId=${requestId}`);

      return NextResponse.json({
        success: true,
        phase: "submitted",
        requestId,
        caption,
        prompt: videoPrompt,
      });
    } catch (err) {
      return NextResponse.json({
        success: false,
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }

  // No wallet = legacy cron-style handler
  return cronHandler(request);
}
